[build-system]
requires = ["setuptools>=42", "setuptools-scm[toml]>=4.1", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
root = "."
write_to = "src/imageProcessor/_version.py"

[tool.setuptools.packages.find]
where = ["src"]

[tool.isort]
combine_as_imports = true
include_trailing_comma = false
multi_line_output = 4
line_length = 79
known_first_party = [
    "karabo", "image_processing", "imageProcessor", "processing_utils",
    "simulatedCameraPy"]
src_paths = ["src"]

[tool.pytest.ini_options]
asyncio_default_fixture_loop_scope = "module"
asyncio_default_test_loop_scope = "function"
asyncio_mode = "auto"

[project.entry-points."karabo.bound_device"]
AutoCorrelator = "imageProcessor.AutoCorrelator:AutoCorrelator"
ImageApplyMask = "imageProcessor.ImageApplyMask:ImageApplyMask"
ImageApplyRoi = "imageProcessor.ImageApplyRoi:ImageApplyRoi"
ImageAverager = "imageProcessor.ImageAverager:ImageAverager"
ImageBackgroundSubtraction = "imageProcessor.ImageBackgroundSubtraction:ImageBackgroundSubtraction"
ImageCrosshair = "imageProcessor.ImageCrosshair:ImageCrosshair"
ImagePatternPicker = "imageProcessor.ImagePatternPicker:ImagePatternPicker"
ImageProcessor = "imageProcessor.ImageProcessor:ImageProcessor"
ImagePicker = "imageProcessor.ImagePicker:ImagePicker"
ImageThumbnail = "imageProcessor.ImageThumbnail:ImageThumbnail"
SimpleImageProcessor = "imageProcessor.SimpleImageProcessor:SimpleImageProcessor"
TwoPeakFinder = "imageProcessor.TwoPeakFinder:TwoPeakFinder"
SaturationMonitor = "imageProcessor.SaturationMonitor:SaturationMonitor"
ImageFlipAndRotate = "imageProcessor.ImageFlipAndRotate:ImageFlipAndRotate"

[project.entry-points."karabo.middlelayer_device"]
ImageToSpectrum = "imageProcessor.ImageToSpectrum:ImageToSpectrum"
ImageNormRoi = "imageProcessor.ImageNormRoi:ImageNormRoi"
BeamShapeCoarse = "imageProcessor.BeamShapeCoarse:BeamShapeCoarse"
ImageNonLinearCorrection = "imageProcessor.ImageNonLinearCorrection:ImageNonLinearCorrection"

[project.optional-dependencies]
test = ["simulatedCameraPy"]

[project]
dynamic = ["version"]
name = "ImageProcessor"
authors = [
    {name = "parenti"},
]
description = ""
readme = "README.md"
dependencies = ["imageProcessing ~= 2.8.4", "processingUtils ~= 1.4.2"]
