#############################################################################
# Author: <andrea.parenti@xfel.eu>
# Created on October 10, 2013
# Copyright (C) European XFEL GmbH Schenefeld. All rights reserved.
#############################################################################

from karabo.common.scenemodel.api import (
    BoxLayoutModel, CheckBoxModel, ComboBoxModel, DisplayLabelModel,
    DisplayListModel, DisplayStateColorModel, EditableListModel,
    IntLineEditModel, LabelModel, LineModel, RectangleModel, SceneModel,
    UnknownWidgetDataModel, write_scene)


def get_scene(deviceId):
    scene00 = LabelModel(font='Source Sans Pro,10,-1,5,50,0,0,0,0,0',
                         foreground='#000000',
                         height=24.0,
                         parent_component='DisplayComponent',
                         text='Enable Crosshair',
                         width=162.0,
                         x=690.0,
                         y=170.0)
    scene01 = LabelModel(font='Source Sans Pro,10,-1,5,50,0,0,0,0,0',
                         foreground='#000000',
                         height=24.0,
                         parent_component='DisplayComponent',
                         text='Auto-Size',
                         width=162.0,
                         x=690.0,
                         y=194.0)
    scene02 = LabelModel(font='Source Sans Pro,10,-1,5,50,0,0,0,0,0',
                         foreground='#000000',
                         height=24.0,
                         parent_component='DisplayComponent',
                         text='Cross-Hair Size',
                         width=162.0,
                         x=690.0,
                         y=218.0)
    scene03 = LabelModel(font='Source Sans Pro,10,-1,5,50,0,0,0,0,0',
                         foreground='#000000',
                         height=24.0,
                         parent_component='DisplayComponent',
                         text='Crosshair Transparency Size',
                         width=162.0,
                         x=690.0,
                         y=242.0)
    scene04 = LabelModel(font='Source Sans Pro,10,-1,5,50,0,0,0,0,0',
                         foreground='#000000',
                         height=24.0,
                         parent_component='DisplayComponent',
                         text='Auto-Thickness',
                         width=162.0,
                         x=690.0,
                         y=266.0)
    scene05 = LabelModel(font='Source Sans Pro,10,-1,5,50,0,0,0,0,0',
                         foreground='#000000',
                         height=24.0,
                         parent_component='DisplayComponent',
                         text='Crosshair Thickness',
                         width=162.0,
                         x=690.0,
                         y=290.0)
    scene06 = LabelModel(font='Source Sans Pro,10,-1,5,50,0,0,0,0,0',
                         foreground='#000000',
                         height=24.0,
                         parent_component='DisplayComponent',
                         text='Auto-Color',
                         width=162.0,
                         x=690.0,
                         y=314.0)
    scene07 = LabelModel(font='Source Sans Pro,10,-1,5,50,0,0,0,0,0',
                         foreground='#000000',
                         height=24.0,
                         parent_component='DisplayComponent',
                         text="Crosshair 'Color'",
                         width=162.0,
                         x=690.0,
                         y=338.0)
    scene0 = BoxLayoutModel(direction=2,
                            height=192.0,
                            width=162.0,
                            x=690.0,
                            y=170.0,
                            children=[
                                scene00, scene01, scene02, scene03, scene04,
                                scene05, scene06, scene07
                            ])
    scene10 = CheckBoxModel(height=24.0,
                            keys=[f'{deviceId}.crosshair.enable'],
                            parent_component='DisplayComponent',
                            width=111.0,
                            x=850.0,
                            y=170.0)
    scene11 = CheckBoxModel(height=24.0,
                            keys=[f'{deviceId}.crosshair.autoSize'],
                            parent_component='DisplayComponent',
                            width=111.0,
                            x=850.0,
                            y=194.0)
    scene12 = DisplayLabelModel(font_size=10,
                                height=24.0,
                                keys=[f'{deviceId}.crosshair.extSize'],
                                parent_component='DisplayComponent',
                                width=111.0,
                                x=850.0,
                                y=218.0)
    scene13 = DisplayLabelModel(font_size=10,
                                height=24.0,
                                keys=[f'{deviceId}.crosshair.intSize'],
                                parent_component='DisplayComponent',
                                width=111.0,
                                x=850.0,
                                y=242.0)
    scene14 = CheckBoxModel(height=24.0,
                            keys=[f'{deviceId}.crosshair.autoThickness'],
                            parent_component='DisplayComponent',
                            width=111.0,
                            x=850.0,
                            y=266.0)
    scene15 = DisplayLabelModel(font_size=10,
                                height=24.0,
                                keys=[f'{deviceId}.crosshair.thickness'],
                                parent_component='DisplayComponent',
                                width=111.0,
                                x=850.0,
                                y=290.0)
    scene16 = CheckBoxModel(height=24.0,
                            keys=[f'{deviceId}.crosshair.autoColor'],
                            parent_component='DisplayComponent',
                            width=111.0,
                            x=850.0,
                            y=314.0)
    scene17 = DisplayLabelModel(font_size=10,
                                height=24.0,
                                keys=[f'{deviceId}.crosshair.color'],
                                parent_component='DisplayComponent',
                                width=111.0,
                                x=850.0,
                                y=338.0)
    scene1 = BoxLayoutModel(direction=2,
                            height=192.0,
                            width=111.0,
                            x=850.0,
                            y=170.0,
                            children=[
                                scene10, scene11, scene12, scene13, scene14,
                                scene15, scene16, scene17
                            ])
    scene20 = CheckBoxModel(height=21.0,
                            keys=[f'{deviceId}.crosshair.enable'],
                            klass='EditableCheckBox',
                            parent_component='EditableApplyLaterComponent',
                            width=141.0,
                            x=970.0,
                            y=170.0)
    scene21 = CheckBoxModel(height=21.0,
                            keys=[f'{deviceId}.crosshair.autoSize'],
                            klass='EditableCheckBox',
                            parent_component='EditableApplyLaterComponent',
                            width=141.0,
                            x=970.0,
                            y=191.0)
    scene22 = IntLineEditModel(height=29.0,
                               keys=[f'{deviceId}.crosshair.extSize'],
                               parent_component='EditableApplyLaterComponent',
                               width=141.0,
                               x=970.0,
                               y=212.0)
    scene23 = IntLineEditModel(height=28.0,
                               keys=[f'{deviceId}.crosshair.intSize'],
                               parent_component='EditableApplyLaterComponent',
                               width=141.0,
                               x=970.0,
                               y=241.0)
    scene24 = CheckBoxModel(height=18.0,
                            keys=[f'{deviceId}.crosshair.autoThickness'],
                            klass='EditableCheckBox',
                            parent_component='EditableApplyLaterComponent',
                            width=141.0,
                            x=970.0,
                            y=269.0)
    scene25 = IntLineEditModel(height=27.0,
                               keys=[f'{deviceId}.crosshair.thickness'],
                               parent_component='EditableApplyLaterComponent',
                               width=141.0,
                               x=970.0,
                               y=287.0)
    scene26 = CheckBoxModel(height=19.0,
                            keys=[f'{deviceId}.crosshair.autoColor'],
                            klass='EditableCheckBox',
                            parent_component='EditableApplyLaterComponent',
                            width=141.0,
                            x=970.0,
                            y=314.0)
    scene27 = IntLineEditModel(height=29.0,
                               keys=[f'{deviceId}.crosshair.color'],
                               parent_component='EditableApplyLaterComponent',
                               width=141.0,
                               x=970.0,
                               y=333.0)
    scene2 = BoxLayoutModel(direction=2,
                            height=192.0,
                            width=141.0,
                            x=970.0,
                            y=170.0,
                            children=[
                                scene20, scene21, scene22, scene23, scene24,
                                scene25, scene26, scene27
                            ])
    scene3 = LabelModel(font='Source Sans Pro,11,-1,5,50,0,1,0,0,0',
                        height=20.0,
                        parent_component='DisplayComponent',
                        text='Crosshair Properties',
                        width=161.0,
                        x=830.0,
                        y=140.0)
    scene4 = LineModel(stroke='#000000',
                       stroke_width=2.0,
                       x=660.0,
                       x1=660.0,
                       x2=660.0,
                       y=20.0,
                       y1=20.0,
                       y2=640.0)
    scene500 = LabelModel(font='Source Sans Pro,10,-1,5,50,0,0,0,0,0',
                          foreground='#000000',
                          height=22.0,
                          parent_component='DisplayComponent',
                          text='DeviceID',
                          width=71.0,
                          x=50.0,
                          y=20.0)
    scene501 = LabelModel(font='Source Sans Pro,10,-1,5,50,0,0,0,0,0',
                          foreground='#000000',
                          height=30.0,
                          parent_component='DisplayComponent',
                          text='State',
                          width=71.0,
                          x=50.0,
                          y=42.0)
    scene502 = LabelModel(font='Source Sans Pro,10,-1,5,50,0,0,0,0,0',
                          foreground='#000000',
                          height=21.0,
                          parent_component='DisplayComponent',
                          text='Status',
                          width=71.0,
                          x=50.0,
                          y=72.0)
    scene50 = BoxLayoutModel(direction=2,
                             height=73.0,
                             width=71.0,
                             x=50.0,
                             y=20.0,
                             children=[scene500, scene501, scene502])
    scene510 = DisplayLabelModel(font_size=10,
                                 height=21.0,
                                 keys=[f'{deviceId}.deviceId'],
                                 parent_component='DisplayComponent',
                                 width=266.0,
                                 x=121.0,
                                 y=20.0)
    scene511 = DisplayStateColorModel(font_size=10,
                                      height=31.0,
                                      keys=[f'{deviceId}.state'],
                                      parent_component='DisplayComponent',
                                      show_string=True,
                                      width=266.0,
                                      x=121.0,
                                      y=41.0)
    scene512 = DisplayLabelModel(font_size=10,
                                 height=21.0,
                                 keys=[f'{deviceId}.status'],
                                 parent_component='DisplayComponent',
                                 width=266.0,
                                 x=121.0,
                                 y=72.0)
    scene51 = BoxLayoutModel(direction=2,
                             height=73.0,
                             width=266.0,
                             x=121.0,
                             y=20.0,
                             children=[scene510, scene511, scene512])
    scene5 = BoxLayoutModel(height=73.0,
                            width=337.0,
                            x=50.0,
                            y=20.0,
                            children=[scene50, scene51])
    scene6 = LabelModel(font='Source Sans Pro,11,-1,5,50,0,1,0,0,0',
                        height=23.0,
                        parent_component='DisplayComponent',
                        text='Marker Properties',
                        width=161.0,
                        x=840.0,
                        y=390.0)
    scene70 = LabelModel(font='Source Sans Pro,10,-1,5,50,0,0,0,0,0',
                         foreground='#000000',
                         height=24.0,
                         parent_component='DisplayComponent',
                         text='Enable Marker',
                         width=141.0,
                         x=690.0,
                         y=430.0)
    scene71 = LabelModel(font='Source Sans Pro,10,-1,5,50,0,0,0,0,0',
                         foreground='#000000',
                         height=24.0,
                         parent_component='DisplayComponent',
                         text='Marker Type',
                         width=141.0,
                         x=690.0,
                         y=454.0)
    scene72 = LabelModel(font='Source Sans Pro,10,-1,5,50,0,0,0,0,0',
                         foreground='#000000',
                         height=24.0,
                         parent_component='DisplayComponent',
                         text='Marker Width',
                         width=141.0,
                         x=690.0,
                         y=478.0)
    scene73 = LabelModel(font='Source Sans Pro,10,-1,5,50,0,0,0,0,0',
                         foreground='#000000',
                         height=24.0,
                         parent_component='DisplayComponent',
                         text='Marker Height',
                         width=141.0,
                         x=690.0,
                         y=502.0)
    scene74 = LabelModel(font='Source Sans Pro,10,-1,5,50,0,0,0,0,0',
                         foreground='#000000',
                         height=24.0,
                         parent_component='DisplayComponent',
                         text='Auto-Thickness',
                         width=141.0,
                         x=690.0,
                         y=526.0)
    scene75 = LabelModel(font='Source Sans Pro,10,-1,5,50,0,0,0,0,0',
                         foreground='#000000',
                         height=24.0,
                         parent_component='DisplayComponent',
                         text='Marker Thickness',
                         width=141.0,
                         x=690.0,
                         y=550.0)
    scene76 = LabelModel(font='Source Sans Pro,10,-1,5,50,0,0,0,0,0',
                         foreground='#000000',
                         height=24.0,
                         parent_component='DisplayComponent',
                         text='Auto-Color',
                         width=141.0,
                         x=690.0,
                         y=574.0)
    scene77 = LabelModel(font='Source Sans Pro,10,-1,5,50,0,0,0,0,0',
                         foreground='#000000',
                         height=23.0,
                         parent_component='DisplayComponent',
                         text="Marker 'Color'",
                         width=141.0,
                         x=690.0,
                         y=598.0)
    scene7 = BoxLayoutModel(direction=2,
                            height=191.0,
                            width=141.0,
                            x=690.0,
                            y=430.0,
                            children=[
                                scene70, scene71, scene72, scene73, scene74,
                                scene75, scene76, scene77
                            ])
    scene80 = CheckBoxModel(height=24.0,
                            keys=[f'{deviceId}.marker.enable'],
                            parent_component='DisplayComponent',
                            width=111.0,
                            x=840.0,
                            y=430.0)
    scene81 = DisplayLabelModel(font_size=10,
                                height=24.0,
                                keys=[f'{deviceId}.marker.type'],
                                parent_component='DisplayComponent',
                                width=111.0,
                                x=840.0,
                                y=454.0)
    scene82 = DisplayLabelModel(font_size=10,
                                height=24.0,
                                keys=[f'{deviceId}.marker.width'],
                                parent_component='DisplayComponent',
                                width=111.0,
                                x=840.0,
                                y=478.0)
    scene83 = DisplayLabelModel(font_size=10,
                                height=24.0,
                                keys=[f'{deviceId}.marker.height'],
                                parent_component='DisplayComponent',
                                width=111.0,
                                x=840.0,
                                y=502.0)
    scene84 = CheckBoxModel(height=23.0,
                            keys=[f'{deviceId}.marker.autoThickness'],
                            parent_component='DisplayComponent',
                            width=111.0,
                            x=840.0,
                            y=526.0)
    scene85 = DisplayLabelModel(font_size=10,
                                height=24.0,
                                keys=[f'{deviceId}.marker.thickness'],
                                parent_component='DisplayComponent',
                                width=111.0,
                                x=840.0,
                                y=549.0)
    scene86 = CheckBoxModel(height=24.0,
                            keys=[f'{deviceId}.marker.autoColor'],
                            parent_component='DisplayComponent',
                            width=111.0,
                            x=840.0,
                            y=573.0)
    scene87 = DisplayLabelModel(font_size=10,
                                height=24.0,
                                keys=[f'{deviceId}.marker.color'],
                                parent_component='DisplayComponent',
                                width=111.0,
                                x=840.0,
                                y=597.0)
    scene8 = BoxLayoutModel(direction=2,
                            height=191.0,
                            width=111.0,
                            x=840.0,
                            y=430.0,
                            children=[
                                scene80, scene81, scene82, scene83, scene84,
                                scene85, scene86, scene87
                            ])
    scene90 = CheckBoxModel(height=24.0,
                            keys=[f'{deviceId}.marker.enable'],
                            klass='EditableCheckBox',
                            parent_component='EditableApplyLaterComponent',
                            width=149.0,
                            x=960.0,
                            y=430.0)
    scene91 = ComboBoxModel(
        height=24.0,
        keys=[f'{deviceId}.marker.type'],
        parent_component='EditableApplyLaterComponent',
        width=149.0,
        x=960.0,
        y=454.0)
    scene92 = IntLineEditModel(height=24.0,
                               keys=[f'{deviceId}.marker.width'],
                               parent_component='EditableApplyLaterComponent',
                               width=149.0,
                               x=960.0,
                               y=478.0)
    scene93 = IntLineEditModel(height=24.0,
                               keys=[f'{deviceId}.marker.height'],
                               parent_component='EditableApplyLaterComponent',
                               width=149.0,
                               x=960.0,
                               y=502.0)
    scene94 = CheckBoxModel(height=23.0,
                            keys=[f'{deviceId}.marker.autoThickness'],
                            klass='EditableCheckBox',
                            parent_component='EditableApplyLaterComponent',
                            width=149.0,
                            x=960.0,
                            y=526.0)
    scene95 = IntLineEditModel(height=24.0,
                               keys=[f'{deviceId}.marker.thickness'],
                               parent_component='EditableApplyLaterComponent',
                               width=149.0,
                               x=960.0,
                               y=549.0)
    scene96 = CheckBoxModel(height=24.0,
                            keys=[f'{deviceId}.marker.autoColor'],
                            klass='EditableCheckBox',
                            parent_component='EditableApplyLaterComponent',
                            width=149.0,
                            x=960.0,
                            y=573.0)
    scene97 = IntLineEditModel(height=24.0,
                               keys=[f'{deviceId}.marker.color'],
                               parent_component='EditableApplyLaterComponent',
                               width=149.0,
                               x=960.0,
                               y=597.0)
    scene9 = BoxLayoutModel(direction=2,
                            height=191.0,
                            width=149.0,
                            x=960.0,
                            y=430.0,
                            children=[
                                scene90, scene91, scene92, scene93, scene94,
                                scene95, scene96, scene97
                            ])
    scene10 = RectangleModel(height=91.0,
                             stroke='#000000',
                             width=351.0,
                             x=40.0,
                             y=10.0)
    scene11 = LineModel(stroke='#000000',
                        stroke_width=2.0,
                        x=670.0,
                        x1=670.0,
                        x2=1110.0,
                        y=380.0,
                        y1=380.0,
                        y2=380.0)
    scene12 = LabelModel(font='Source Sans Pro,11,-1,5,50,0,1,0,0,0',
                         height=34.0,
                         parent_component='DisplayComponent',
                         text='Crosshair/Marker Position',
                         width=221.0,
                         x=830.0,
                         y=10.0)
    scene13 = UnknownWidgetDataModel(
        attributes={
            '{http://karabo.eu/scene}colormap':
            'none',
            '{http://karabo.eu/scene}class':
            'DisplayComponent',
            '{http://karabo.eu/scene}widget':
            'ImageCrossHairGraph',
            '{http://karabo.eu/scene}keys':
                (f'{deviceId}.ppOutput.schema.data.image,'
                 f'{deviceId}.position')
        },
        height=461.0,
        keys=[
            f'{deviceId}.ppOutput.schema.data.image',
            f'{deviceId}.position'
        ],
        klass='ImageCrossHairGraph',
        parent_component='DisplayComponent',
        width=611.0,
        x=10.0,
        y=140.0)
    scene14 = LineModel(stroke='#000000',
                        stroke_width=2.0,
                        x=670.0,
                        x1=670.0,
                        x2=1110.0,
                        y=130.0,
                        y1=130.0,
                        y2=130.0)
    scene150 = LabelModel(font='Source Sans Pro,10,-1,5,50,0,0,0,0,0',
                          foreground='#000000',
                          height=31.0,
                          parent_component='DisplayComponent',
                          text='Crosshair/Marker Position',
                          width=153.0,
                          x=690.0,
                          y=50.0)
    scene151 = LabelModel(font='Source Sans Pro,10,-1,5,50,0,0,0,0,0',
                          foreground='#000000',
                          height=31.0,
                          parent_component='DisplayComponent',
                          text='Crosshair/Marker Rotation',
                          width=153.0,
                          x=690.0,
                          y=81.0)
    scene15 = BoxLayoutModel(direction=2,
                             height=62.0,
                             width=153.0,
                             x=690.0,
                             y=50.0,
                             children=[scene150, scene151])
    scene160 = DisplayListModel(height=31.0,
                                keys=[f'{deviceId}.position'],
                                parent_component='DisplayComponent',
                                width=111.0,
                                x=850.0,
                                y=50.0)
    scene161 = DisplayLabelModel(font_size=10,
                                 height=31.0,
                                 keys=[f'{deviceId}.rotation'],
                                 parent_component='DisplayComponent',
                                 width=111.0,
                                 x=850.0,
                                 y=81.0)
    scene16 = BoxLayoutModel(direction=2,
                             height=62.0,
                             width=111.0,
                             x=850.0,
                             y=50.0,
                             children=[scene160, scene161])
    scene170 = EditableListModel(
        height=31.0,
        keys=[f'{deviceId}.position'],
        parent_component='EditableApplyLaterComponent',
        width=123.0,
        x=970.0,
        y=50.0)
    scene171 = IntLineEditModel(height=31.0,
                                keys=[f'{deviceId}.rotation'],
                                parent_component='EditableApplyLaterComponent',
                                width=123.0,
                                x=970.0,
                                y=81.0)
    scene17 = BoxLayoutModel(direction=2,
                             height=62.0,
                             width=123.0,
                             x=970.0,
                             y=50.0,
                             children=[scene170, scene171])
    scene = SceneModel(height=700.0,
                       width=1200.0,
                       children=[
                           scene0, scene1, scene2, scene3, scene4, scene5,
                           scene6, scene7, scene8, scene9, scene10, scene11,
                           scene12, scene13, scene14, scene15, scene16,
                           scene17,
                       ])
    return write_scene(scene)
